baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://ellekasai.com" # the base hostname & protocol for your site
title: "Elle Kasai"
photo: "https://dl.dropboxusercontent.com/u/31114442/images.ellekasai.com/ellekasai.jpg"

# This is used by feed.xml. Uncomment if you want to use it.
description: "Elle Kasai's Peronal Blog."

gems:
  - jemoji
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
permalink: "posts/:title"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
