title: Elle Kasai
description: 笠井枝理依のブログ｡UIデザイナーを目指して奮闘中!
permalink: /posts/:title
markdown: redcarpet

# Used by liquid
settings:
  num_posts_on_index: 3
  host_name: ellekasai.com
  debug: false
  # Comment this out and specify image URL for og:image.
  # Otherwise, og:image will not be set.
  # og_image: http://example.com/image.jpg
author:
  name: Elle Kasai
  twitter: Krizel77
  github: ellekasai
  website: about.me/elle_kasai
  email: elle.kasai@gmail.com
code:
  google_analytics: UA-36051690-2
  fb_admins: 1214763701